---
title: JavaScript Full Course for free 🌐 (2024) - YouTube
description: >-
  Enjoy the videos and music that you love, upload original content and share it
  all with friends, family and the world on YouTube.
author: YouTube
source: https://www.youtube.com/
created: "2025-09-03"
tags:
  - hover-notes
  - youtube
---

```javascript
try {
  console.log("hello");
  // NETWORK ERRORS
  // PROMISE REJECTION
  // SECURITY ERRORS
}
catch (error) {
  console.error(error);
}
finally {
  // CLOSE FILES
  // CLOSE CONNECTIONS
  // RELEASE RESOURCES
  console.log("This always executes");
}
console.log("You have reached the end!");
```
## Error Handling - User Input
- Errors can also happen when accepting user input.
- We don't know what the user will type.
- Could be a malicious script.
### Example: Division

```javascript
const dividend = window.prompt("Enter a dividend:");
const divisor = window.prompt("Enter a divisor:");
```

```javascript
const result = dividend / divisor;
console.log(result);
```
- If you attempt to divide by zero in JavaScript, you get `Infinity`.
- You can intentionally cause errors to handle them with `try...catch`.
- Code that takes user input is considered dangerous and should be placed in a `try` block.

```javascript
try {
  const dividend = window.prompt("Enter a dividend:");
  const divisor = window.prompt("Enter a divisor:");

  const result = dividend / divisor;
  console.log(result);
}
catch (error) {
  console.error(error);
}
```

```javascript
const result = dividend / divisor;
console.log(result);
```
- If you attempt to divide by zero in JavaScript, you get `Infinity`.
- You can intentionally cause errors to handle them with `try...catch`.
- Code that takes user input is considered dangerous and should be placed in a `try` block.

```javascript
try {
  const dividend = window.prompt("Enter a dividend:");
  const divisor = window.prompt("Enter a divisor:");

  const result = dividend / divisor;
  console.log(result);
}
catch (error) {
  console.error(error);
}
```
- Mathematically speaking, we can't divide a number by zero.

```javascript
const dividend = window.prompt("Enter a dividend:");
const divisor = window.prompt("Enter a divisor:");

const result = dividend / divisor;
console.log(result);
```
- With division, a dividend is the number that is being divided, and we need a divisor.
- A divisor is the number we're dividing by.

```javascript
const divisor = window.prompt("Enter a divisor:");

const result = dividend / divisor;
console.log(result);
```
- If you attempt to divide by zero in JavaScript, you get `Infinity`.
- You can intentionally cause errors to handle them with `try...catch`.
- Code that takes user input is considered dangerous and should be placed in a `try` block.
### Error Handling - Intentionally Causing Errors
- Intentionally cause errors with `try...catch`
- Using an `if` statement can help cause an error.

```javascript
try {
  const dividend = window.prompt("Enter a dividend:");
  const divisor = window.prompt("Enter a divisor:");

  if (divisor == 0) {
    throw new Error("You can't divide by zero!");
  }

  const result = dividend / divisor;
  console.lag(result);
}
catch (error) {
  console.error(error);
}

console.log("You have reached the end!");
```
### Error Handling - Throwing Errors
- We can call the error constructor to construct a new error object.
- Within the constructor, we have one argument to pass in:
    - A message.
    - What is the error going to say?
- Example:

```javascript
throw new Error("You can't divide by zero!");
```
- The program isn't interrupted.
- If someone types in something that's not a number, it will result in NaN (Not a Number).
- To address this, we can typecast the prompt as a number:

```javascript
const dividend = Number(window.prompt("Enter a dividend:"));
const divisor = Number(window.prompt("Enter a divisor:"));
```
### Error Handling - Not a Number
- Check if the input is `NaN`

```javascript
try {
  const dividend = Number(window.prompt("Enter a dividend:"));
  const divisor = Number(window.prompt("Enter a divisor:"));

  if (divisor == 0) {
    throw new Error("You can't divide by zero!");
  }

  if(isNaN(dividend) || isNaN(divisor)){
    throw new Error("Values must be a number")
  }

  const result = dividend / divisor;
  console.log(result);
}
catch (error) {
  console.error(error);
}

console.log("You have reached the end!");
```
- If the dividend or the divisor is `NaN`, throw a new error.
- Error objects can be created and handled in certain situations.
- After throwing an error (e.g., when entering non-numeric values like "pizza"), the program's execution is not interrupted.
- The `catch` block handles the error, and the code after the `try...catch` block continues to run (e.g., `console.log("You have reached the end!");`).
- Error objects provide a way to define and handle specific error conditions within your code.
### Error Handling
- An `Error` is an object that represents a problem.
- Errors often occur with user input or establishing a connection.
- Use `try`, `catch`, and optionally `finally` blocks to handle errors.
- `finally` blocks are used mostly for cleanup (ex. close files, close connections, release resources).
- Place code that can cause an error within a `try` block.
- Catch any errors that happen.

```javascript
try {
  const dividend = Number(window.prompt("Enter a dividend: "));
  const divisor = Number(window.prompt("Enter a divisor: "));

  if (divisor == 0) {
    throw new Error("You can't divide by zero!");
  }

  if(isNaN(dividend) || isNaN(divisor)){
    throw new Error("Values must be a number")
  }

  const result = dividend / divisor;
  console.log(result);
}
catch(error){
  console.error(error);
}

console.log("You have reached the end!");
```